### ISSUE TITLE
Serialization to a common format

### ISSUE THREAD

**Issue by dylon** [universal-automata/liblevenshtein-java#4]
- It should be sharable across programming languages
- YAML or related should work well

**Comment by alexander-myltsev** [comment]
What algorithm should be behind? http://www.aclweb.org/anthology/J00-1002.pdf ?

**Comment by alexander-myltsev** [comment]
What kind of serialization is intended? Entire `Transducer` and all related structures?

**Comment by dylon** [comment]
The transducer itself is tabular (rules-based), so no graphical structure is required to store it.  The dictionary automaton and some parameters (e.g. max edit distance) are all that need to be serialized.  Java provides a nice suite of serialization utilities, but only JVM-based languages can read its byte code.  There are some utilities to serialize Java-based structures to and from YAML, which are what I'm primarily considering.

**Comment by dylon** [comment]
Done.  I've gone with Google Protocol Buffers and a minimal set of attributes.

**Comment by alexander-myltsev** [comment]
Please, refer a doc or commit at least to understand how to use it.

**Comment by jbaiter** [comment]
It's really simple:

```java
Transducer transducer;
// ...
// Build transducer
// ...
ProtobufSerializer serializer = new ProtobufSerializer();
OutputStream os = new FileOutputStream("transducer.bin");
os.write(serializer.serialize(transducer);
```

Note that there's currently an issue with serializing transducer with deep dictionaries: https://github.com/universal-automata/liblevenshtein-java/issues/40

**Comment by dylon** [comment]
As @jbaiter described, it is really simple.  For another example, here's a unit test demonstrating how to (de)serialize dictionaries to and from byte arrays: [DawgTest.java](https://github.com/universal-automata/liblevenshtein-java/blob/2.2.0/src/test/java/com/github/dylon/liblevenshtein/collection/dawg/DawgTest.java#L84-L98)

The preferred serializer is [ProtobufSerializer](https://github.com/universal-automata/liblevenshtein-java/blob/master/src/main/java/com/github/dylon/liblevenshtein/serialization/ProtobufSerializer.java).

There are other options for serializing to/from streams.  You could do the following:

```java
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import com.github.dylon.liblevenshtein.collection.dawg.DawgNode;
import com.github.dylon.liblevenshtein.levenshtein.Transducer;
import com.github.dylon.liblevenshtein.serialization.ProtobufSerializer;
import com.github.dylon.liblevenshtein.serialization.Serializer;

// ...
final SortedDawg dictionary = buildDictionary();
final Transducer transducer = buildTransducer(dictionary);

final Serializer serializer = new ProtobufSerializer();

final Path serializedTransducerPath = Paths.get("/path/to/transducer.proto.bytes");
try (final OutputStream stream = Files.newOutputStream(serializedTransducerPath)) {
    serializer.serialize(transducer, serializedTransducerPath);
}

// If you'd prefer to serialize your dictionary:
final Path serializedDictionaryPath = Paths.get("/path/to/dictionary.proto.bytes");
try (final OutputStream stream = Files.newOutputStream(serializedDictionaryPath)) {
    serializer.serialize(dictionary, stream);
}

final Transducer deserializedTransducer;
try (final InputStream stream = Files.newInputStream(serializedTransducerPath)) {
    deserializedTransducer = serializer.deserialize(Transducer.class, stream);
}

// If you'd prefer to deserialize your dictionary
final SortedDawg deserializedDictionary;
try (final InputStream stream = Files.newInputStream(serializedDictionaryPath)) {
    deserializedDictionary = serialized.deserialize(SortedDawg.class, stream);
}
// ...
```

Please refer to the Javadoc for more info: [Serializer](http://universal-automata.github.io/liblevenshtein-java/docs/javadoc/2.2.1/com/github/dylon/liblevenshtein/serialization/Serializer.html)

**Comment by dylon** [comment]
I'll add support for (de)serializing to/from Paths, directly, in the next release.

**Comment by dylon** [comment]
For really deep dictionaries, you may use the [BytecodeSerializer](http://universal-automata.github.io/liblevenshtein-java/docs/javadoc/2.2.1/com/github/dylon/liblevenshtein/serialization/BytecodeSerializer.html).  I'm finishing a command-line interface that will let you play around with liblevenshtein and convert dictionaries from various formats to others.  It's almost done, I just need to finish some integration tests.

**Comment by dylon** [comment]
I still need to finish the integration tests, but I've manually tested it well.  Here's the command-line client (see its README): [liblevenshtein-java-cli](https://github.com/universal-automata/liblevenshtein-java-cli)
