### ISSUE TITLE
Is a transducer thread-safe ?

### ISSUE THREAD

**Issue by christopheblin** [universal-automata/liblevenshtein-java#79]
Can I share a global transducer in my web application or do I need to build one transducer for each request ?

Currently, I use a shared transducer and it does not seem to cause troubles, however I am concerned that it can lead to troubles in the future (when more concurrency for example)

The problem if I need to build one transducer for each request is that there should be a way to share the dictionary (because it is time consuming to build it).

Something like (in kotlin)
 
    val dictionary = DictionaryBuilder()
            .words(dictionary, /*isSorted*/true)
            .build<Candidate>()

    fun spellcheck(word: String): List<String> {
        val transducer = TransducerBuilder()
            .dictionary(dictionary, true)
            .algorithm(Algorithm.TRANSPOSITION)
            .defaultMaxDistance(2)
            .includeDistance(true)
            .build<Candidate>()
        return transducer
            .transduce(word)
            .sortedBy { it.distance() }
            .map { it.term() }
    }

**Comment by dylon** [comment]
The current implementation of the transducer is not thread-safe.  It generates one candidate at a time by searching the intersection of the dictionary automaton and the Levenshtein automaton.  If you want to parallelize the algorithm, you should split your dictionary into as many partitions as you have threads or processes, give each its own transducer, and combine the spelling candidates for a query term in a map-reduce fashion.

https://github.com/universal-automata/liblevenshtein-java/blob/master/src/main/java/com/github/liblevenshtein/transducer/LazyTransducerCollection.java#L21-L25

**Comment by christopheblin** [comment]
Sorry to revive this thread :)

My problem is not that the dictionary is huge but that many threads spellcheck different words at the same time

After investigation, I found that a "slow" part is DawgFactory.build() which, in my case, take around 60ms for each spellchecks (on a total of about 560ms)

What I've done is that I share the Dawg between threads (not the transducer, just the dawg) so it took around 500ms

Is that ok ?

```
companion object {
    val dictionnary = DawgFactory().build(Db.loadTerms(), true)

   fun spellcheck(w: String) = TransducerBuilder()
                .dictionary(dictionary, /*isSorted*/true) //under the hood, as dictionary is already a Dawg, nothing is computed here
                .algorithm(Algorithm.TRANSPOSITION)
                .includeDistance(true)
                .build<Candidate>()
                .transduce(word, 2)
}

//note that companion object in kotlin is like static in java
```

**Comment by dylon** [comment]
Yes, that's exactly what you should do since the dictionary cannot be mutated post-construction.  You may also serialize it to/from disk so you don't have to build it again. 
 Take a look at the documentation on using the `ProtobufSerializer`:

https://github.com/universal-automata/liblevenshtein-java/blob/gh-pages/docs/wiki/3.0.0/usage.md
